server:
  port: 8888
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vehicle-rental-db
    username: postgres
    password: q11q
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: false
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    secret:
      key: 185f8db32271fe25f561a6fc938b2e264306ec304eda518007d1764826381969

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  info:
    title: Product Catalog API
    description: API documentation for the Product Catalog service
    version: 1.0.0

logging:
  level:
    org:
      springframework:
        web:
          DEBUG
      apache:
        catalina:
          DEBUG

rental:
  max-discount-percent: 80